notifications:
  email:
    on_success: never
    on_failure: always

sudo: false
language: python

# Linux with different python versions
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

# Badges for distinguishing operating systems in builds
env: BADGE=linux

# Include Other operating systems
matrix:
    include:
        - name: "Linux with Python: pypy"
          os: linux
          python: "pypy"
          env: BADGE=linux
          before_install:
            - sudo add-apt-repository universe
            - sudo apt update
            - sudo apt install gfortran libopenblas-dev liblapack-dev python-dev
            - pypy --version
            - pypy -m pip install --upgrade pip
            - pypy -m pip install --upgrade pytest-cov
            - pypy -m pip install codecov
          install:
            - pypy -m pip install -r requirements.txt
            - pypy -m pip install -e .

        - name: "macOSX with Python: 2.7"
          os: osx
          osx_image: xcode11
          language: shell
          sudo: true
          env:
            - PYTHON_VERSION=2.7
            - BADGE=osx

        - name: 'macOSX with Python: 3.7'
          os: osx
          osx_image: xcode11
          language: shell
          env:
            - PYTHON_VERSION=3.7
            - BADGE=osx
          before_install:
            - python3 --version
            - python3 -m pip install --upgrade pip
            - python3 -m pip install --upgrade pytest-cov
            - python3 -m pip install codecov
          install:
            - python3 -m pip install -r requirements.txt
            - python3 -m pip install -e .
          script:
            - python3 -m pytest --cov-report=xml --cov=tests/

        - name: "Windows with Python: 3.8"
          os: windows
          language: shell
          before_install:
            - choco install python --version 3.8.0
            - python --version
            - python -m pip install --upgrade pip
            - python -m pip install --upgrade pytest-cov
            - python -m pip install codecov
          env:
            - PATH=/c/Python38:/c/Python38/Scripts:$PATH
            - BADGE=windows

        # - stage: deploy
        #   python: 3.8
        #   before_install:
        #     - gem install travis -N
        #     - python -m pip install --upgrade pip
        #   install:
        #     - python -m pip install -r requirements.txt
        #     - python -m pip install -e .[dev]
        #     - python -m pip install -e .[docs]
        #   script:
        #     - python -m pytest --cov-report=xml --cov=tests/
        #     - make -C docs/ html
        #     - touch docs/_build/html/.nojekyll
        #   after_success:
        #     - codecov
        #   deploy:
        #       - provider: pages
        #         verbose: true
        #         skip_cleanup: true
        #         github_token: $GITHUB_TOKEN
        #         local_dir: ./docs/_build/html
        #         keep_history: true
        #         on:
        #             branch: master

# These only apply to the above jobs that before_install is not declared for them in the above.
before_install:
  - python --version
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade pytest-cov
  - python -m pip install codecov

# These only apply to the above jobs that install is not declared for them in the above.
install:
  - python -m pip install -r requirements.txt
  - python -m pip install -e .

# These only apply to the above jobs that script is not declared for them in the above.
script:
  - python -m pytest --cov-report=xml --cov=tests/

after_success:
  - codecov
