name: deploy-docker

on:
    push:
        branches:
            - main
    release:
        types: 
            - published

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  push: true
                  file: ./docker/Dockerfile
                  tags: sameli/glearn:latest

            - name: Image digest
              run: echo ${{ steps.docker_build.outputs.digest }}
